WebApplication05/Areas/Admin/Controllers/SocialMediaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication05.Areas.Admin.ViewModels.SocialMediaAdminVMs;
using WebApplication05.Contexts;
using WebApplication05.Models;

namespace WebApplication05.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles = "SuperAdmin, Admin")]
public class SocialMediaController : Controller
{
    Cial01DbContext _db { get; }
    UserManager<AppUser> _userManager {  get; }

    public SocialMediaController(Cial01DbContext db, UserManager<AppUser> userManager)
    {
        _db = db;
        _userManager = userManager;
    }

    // GET: SocialMediaController
    public ActionResult Index()
    {
        return View(this._db.SocialMedias.Include(sm => sm.SocialMediaType).Include(sm => sm.AppUser).
            Select(sm => new SocialMediaAdminVM(sm)));
    }

    // GET: SocialMediaController/Create
    public ActionResult Create()
    {
        ViewBag.Types = new SelectList(this._db.SocialMediaTypes, "Id", "TypeName");
        //ViewBag.Users = new SelectList(this._db.AppUsers, "Id", "UserName");
        return View();
    }

    // POST: SocialMediaController/Create
    [HttpPost]
    public async Task<ActionResult> Create(SocialMediaCreateVM vm)
    {
        if (!await this._db.SocialMediaTypes.AnyAsync(smt => smt.Id == vm.SocialMediaTypeId)) ModelState.AddModelError("", "No such Social media type");
        if (!ModelState.IsValid)
        {
            ViewBag.Types = new SelectList(this._db.SocialMediaTypes, "Id", "TypeName");
            //ViewBag.Users = new SelectList(this._db.AppUsers, "Id", "UserName");
            return View(vm);
        }

        SocialMedia mediaLink = vm.ToMediaLink();
        mediaLink.AppUserId = (await this._userManager.FindByNameAsync(User.Identity.Name)).Id;

        await this._db.SocialMedias.AddAsync(mediaLink);
        await this._db.SaveChangesAsync();

        return RedirectToAction(nameof(Index));
    }

    // GET: SocialMediaController/Edit/5
    public async Task<ActionResult> Edit(int id)
    {
        SocialMedia mediaLink = await this._db.SocialMedias.FindAsync(id);
        if (mediaLink == null) return NotFound();

        ViewBag.Types = new SelectList(this._db.SocialMediaTypes, "Id", "TypeName");
        //ViewBag.Users = new SelectList(this._db.AppUsers, "Id", "UserName");
        return View(new SocialMediaEditVM(mediaLink));
    }

    // POST: SocialMediaController/Edit/5
    [HttpPost]
    public async Task<ActionResult> Edit(int id, SocialMediaEditVM vm)
    {
        SocialMedia mediaLink = await this._db.SocialMedias.FindAsync(id);
        if (mediaLink == null) return NotFound();
        if (!await this._db.SocialMediaTypes.AnyAsync(smt => smt.Id == vm.TypeId)) ModelState.AddModelError("", "No such Social media type");
        if (!ModelState.IsValid)
        {
            ViewBag.Types = new SelectList(this._db.SocialMediaTypes, "Id", "TypeName");
            //ViewBag.Users = new SelectList(this._db.AppUsers, "Id", "UserName");
            return View(vm);
        }

        mediaLink.SocialMediaTypeId = vm.TypeId == null ? mediaLink.SocialMediaTypeId : (int)vm.TypeId;
        mediaLink.Link = vm.Link;

        this._db.Update(mediaLink);
        await this._db.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    // GET: SocialMediaController/Delete/5
    public async Task<ActionResult> Delete(int id)
    {
        SocialMedia mediaLink = await this._db.SocialMedias.FindAsync(id);
        if (mediaLink == null) return NotFound();

        mediaLink.IsActive = !mediaLink.IsActive;
        this._db.Update(mediaLink);
        await this._db.SaveChangesAsync();

        return RedirectToAction(nameof(Index));
    }
}

WebApplication05/Areas/Admin/Controllers/SocialMediaTypeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApplication05.Areas.Admin.ViewModels.SocialMediaAdminVMs;
using WebApplication05.Contexts;
using WebApplication05.Extensions;
using WebApplication05.Modelsl;

namespace WebApplication05.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles = "SuperAdmin, Admin")]
public class SocialMediaTypeController : Controller
{
    Cial01DbContext _db { get; }

    public SocialMediaTypeController(Cial01DbContext db)
    {
        _db = db;
    }

    // GET: SocialMediaTypeController
    public ActionResult Index()
    {
        return View(this._db.SocialMediaTypes.Select(smt => new SocialMediaTypeAdminVM(smt)));
    }

    // GET: SocialMediaTypeController/Create
    public ActionResult Create()
    {
        return View();
    }

    // POST: SocialMediaTypeController/Create
    [HttpPost]
    public async Task<ActionResult> CreateAsync(SocialMediaTypeCreateVM vm)
    {
        if (vm.ImageFile == null || !vm.ImageFile.IsCorrectType()) ModelState.AddModelError("", "No image provided");
        if (!ModelState.IsValid) return View(vm);

        SocialMediaType mediaType = await vm.ToMediaTypeAsync();
        await this._db.SocialMediaTypes.AddAsync(mediaType);
        await this._db.SaveChangesAsync();

        return RedirectToAction(nameof(Index));
    }

    // GET: SocialMediaTypeController/Delete/5
    public async Task<ActionResult> DeleteAsync(int id)
    {
        SocialMediaType mediaType = await this._db.SocialMediaTypes.FindAsync(id);
        if (mediaType == null) return NotFound();

        string path = Path.Combine(FileExtensions.RootPath, mediaType.ImagePath);

        if (System.IO.File.Exists(path))
        {
            System.IO.File.Delete(path);
        }
        
        this._db.SocialMediaTypes.Remove(mediaType);
        await this._db.SaveChangesAsync();

        return RedirectToAction(nameof(Index));
    }
}

WebApplication05/Areas/Admin/Views/SocialMediaType/Create.cshtml
@model SocialMediaTypeCreateVM
@{
    ViewData["Title"] = "Create media type";
}
@section Style
{
    <link rel="stylesheet" href="~/style.css">
}

<div class="wrapper">
    <form method="post" enctype="multipart/form-data">
        <div class="input-box">
            <input asp-for="TypeName" placeholder="Enter media name" required>
            <span asp-validation-for="TypeName"></span>
        </div>
        <div class="input-box">
            <input asp-for="ImageFile" accept="image/*" required>
            <span asp-validation-for="ImageFile"></span>
        </div>
        <div asp-validation-summary="ModelOnly"></div>
        <div class="input-box button">
            <input type="Submit" value="Create">
        </div>
    </form>
</div>

WebApplication05/Areas/Admin/Views/SocialMediaType/Edit.cshtml
@model SocialMediaTypeCreateVM
@{
    ViewData["Title"] = "Create media type";
}
@section Style
{
    <link rel="stylesheet" href="~/style.css">
}

<div class="wrapper">
    <form method="post" enctype="multipart/form-data">
        <div class="input-box">
            <input asp-for="TypeName" placeholder="Enter media name" required>
            <span asp-validation-for="TypeName"></span>
        </div>
        <div class="input-box">
            <input asp-for="ImageFile" accept="image/*" required>
            <span asp-validation-for="ImageFile"></span>
        </div>
        <div asp-validation-summary="ModelOnly"></div>
        <div class="input-box button">
            <input type="Submit" value="Create">
        </div>
    </form>
</div>

WebApplication05/Areas/Admin/Views/SocialMediaType/Index.cshtml
@model IEnumerable<SocialMediaTypeAdminVM>
@section Style
{
    <!-- Custom styles for this page -->
    <link href="~/admin/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
}
@section Script
{
    <!-- Page level plugins -->
    <script src="~/admin/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/admin/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/admin/js/demo/datatables-demo.js"></script>
}
@{
    ViewData["Title"] = "Media Types";
}

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Tables</h1>
<a asp-action="Create">Create type</a><br>
<a asp-action="Index" asp-controller="SocialMedia">View Link editor</a>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>TypeName</th>
                        <th>Image</th>
                        <th>Delete</th>
                        <th>Edit</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Id</th>
                        <th>TypeName</th>
                        <th>Image</th>
                        <th>Delete</th>
                        <th>Edit</th>
                    </tr>
                </tfoot>
                <tbody>
                    @if (Model != null)
                    {
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.TypeName</td>
                                <td><img src="~/@item.ImagePath"></td>
                                <td><a asp-action="Delete" asp-route-id="@item.Id">Delete</a></td>
                                <td><a asp-action="Edit" asp-route-id="@item.Id">Edit</a></td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>